# Database settings
mysql_root_password: "zabbixDBroot"
zabbix_db_name: "zabbix"
zabbix_db_user: "zabbix"
zabbix_db_password: "secretPass"

# Zabbix settings
zabbix_server_host: "10.130.2.100"
zabbix_version: "7.2"
zabbix_timezone: "Europe/Moscow"

# Application settings
php_memory_limit: "128M"
php_max_execution_time: "300"
